package com.everything.strings.similarity;

import org.apache.commons.text.similarity.LevenshteinDistance;

import java.util.concurrent.TimeUnit;

/**
 * User: Makar Kalancha
 * Date: 01/01/2018
 * Time: 19:46
 */
public class OrganizationSimilarity {
    public static void main(String[] args) {
        LevenshteinDistance levenshteinDistance = new LevenshteinDistance();
        long start = System.nanoTime();
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "1111, rue Saint-Urbain, bureau 111, H2Z 1Y6");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "123 Front St West");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "41074");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "41078");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "41080");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "41085");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "8000 ch de la Savane J3Y 8Y9");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "A Votre Sante");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "A&W");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "ADESA");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "AMR Fruterie");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "AMT");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "ATM");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Abbaye de St-Benoit du Lac");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Academie");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Acanac");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Accueil ile Bonaventure");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Acquisio");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Adonis");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Aeroports de Montreal");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Ailes");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Akhavan");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Al Wadi");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Alex Kovalev");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Alex Nihon");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Alina Seremet");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Altima Telecom");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Amazon");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Amazon.ca");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Amco Ovia Petroleum Ltd");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "American Express Costco");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Amir");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Amos Pewterers Limited");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Amour Du Pain");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Andre Joseph Abattage  Pro");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Angrignon");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Animal Expert");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Anna Chertkov");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Antirouille Metropolitain");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Aqua");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Archambault Brossard");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Ardene");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Armee De Salut");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Atlantic Superstore");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Atlas-taxi 514-485-4888");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Atwater");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Au Pain Dore");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Auberge Dragon Rouge");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Auberge Le Campagnard");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Audiologle centre ouest");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "AutomotiveTouchup.com");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Avant Garde Solution Inc.");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Aeroport de Montreal");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Aeroports de Montreal");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Bad Idea T-Shirt");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Balkani");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Bar");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Bar Laitier du Rocher");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Bar Populaire");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Bar populaire");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Baskin Robbins");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Bateau Electrique");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Bateaux Crois J Cloutier");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Beauce Carnaval Inc");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Bebe Depot Plus");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Bell");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Bellevue Ophtalmologie");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Bentley");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Bently");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Bertrand Allain");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Best Buy");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Best Western Gregory Hotel: 8315 4th Avenue, Brooklyn, NY 11209, USA");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Betonel");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Betonel Dulux");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Bijou-Cree");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Bijouterie Bartier");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Bijouterie Cathy");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Bijouterie Monaco");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Biodome");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Bizou");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Blue Cross");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Blue cross");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Bobebe");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Bol de fruits de qualite");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Boulangerie La Midore");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Boulangerie Snowdon");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Boutique Eclipse");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Boutique Le Macareux");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Brasserie Dieu Du Ciel");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Brault & Martineau");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Brault & Matineau");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Breault Serrurier Securete");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Brulerie St-Denis");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Btq Florale Marie Eve");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Buffet Des Continents");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Buffet Fu Lam");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Buffet Oriental");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Bureau En Gros");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Bureau en Gros");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Burger King");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "CAA");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "CCTB/PFCE");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "CENTRE DENTAIRE CENTRALE LASALLE QC");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "CLUB DE SOCCER ST HUBERT SAINT-HUBERT QC");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "CMR");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "COMM.SCOLAIRE MVICTORIN TAXE");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "CRA");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "CSC*US EMBASSY MRV FEE 703-889-2611 QC");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "CSST");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "CTC/Fuelco");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Caban");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Cafe 92");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Cafe Cito 92");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Cafe Depot");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Cafe St-Paul");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Cafe Starbucks");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Cafe Vienne");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Cafeden");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Cafeteria Cegep");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Cafe 92");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Cafe Epoca");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Canada");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Canada Computers");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Canada Foreign Affaires");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Canada Post");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Canadian Museum of Civilization");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Canadian Tire");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Capital One");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Cardon");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Carina Petrosian");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Casey's Mont-Tremblant");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Cegep Saint-Jean-sur-Richelieu");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Cegep St-Jean");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Centre Bell");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Centre De Jardin");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Centre Dentair Letourn: 1100 av Beaumont, H3P 3E5");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Centre Dentair: 7584 rCentrale ste2 H8P 1K5");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Centre Dentaire Centrale");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Centre Hi-Fi");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Centre Saint-Paul");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Centre Sportif");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Centre Sportif Notre-Dame-De-Grace");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Centre de Jardin Brossard");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Centre des science de Montreal");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Centre sportif Rosanne-Laflamme");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Champion Lanes");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "ChannelMasterStore.com");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Charbonneau Claude");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Charcuterie Transilvania");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Chateau Rouge");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Chatr");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Chezticlaude");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "China Garden");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Cineplex");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Cinq-a-sept");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Cirque de Soleil");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Cirque du Soleil");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Clarke Medical Imaging");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Clinic Medic Elle");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Club Piscine");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Club Piscine Plus");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Club Tissus");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Coastal Inn Dartmouth (379 Windmill Road, B3A 1J6 Dartmouth)");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Coco Bon");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Coco Pazzo Boutique");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "CocoBon");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Cocobun");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Coffee");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Coiffure Belle Angelique");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "College Saint-Jean-Sur-Richelieu");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Complex les Ailes");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Concordia University");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Continental Place Alexis Nihon");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Cool As A Moose");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Coopsco St-Jean");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Coopsco-St-Jean");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Coopso St-Jean");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Copoli Restaurant");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Costco");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Couche Tard");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Couche Tard Inc");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Crazy Cmak");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Cremazie");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Croisiere AML");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Croix Blue");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Cultures");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Cyclorama");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Dad's Bagels");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Dairy Queen");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "David's Tea");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Davids Tea");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "DeSerres");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Delilah");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Dell");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Dell.ca");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Depanneur Despres et Desp");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Desjardins");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Desjardins Auto Insurance");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Desjardins Property Insurance");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Destinatin Dollar");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Dollar Ann Fang Depot");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Dollar Store");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Dollar Ville");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Dollarama");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Dollarama to Industrielle Alliance");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Dollarama гречанка");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Dominique Voyer");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Domino's Pizza");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Double Pizza");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Dunkin Donut");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Depanneur");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Ecco");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Econolodge Miramichi (365 Pleasant Street, E1V 1X4 Miramichi)");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Eko Rimouski");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Eldorado Import");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Ella's Deli");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Employment Insurance");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "En Gros");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Energie Cardio");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Epicerie chez Paul");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Epicerie du vieux Quebec");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Espace pour la vie");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Esposito");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Esso");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Evenko.ca");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Exo Fruits");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "FTQ");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Fabricville");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Falls Parking");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Familiprix");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Fan's Restaurant");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Ferme Quinn");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Festijets");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Fido");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Fleuriste Tigon");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Fleuriste de L'Aeroport DFL Inc");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Fleuriste de l'Aeroport");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Flex");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Florist West");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Flying J");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Foot Locker");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Forever 21");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Forever21");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Frechette Fruits Et Legumes");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "French");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Fruiterie 440");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Fruiterie Inc.");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Fruits & Legumes Grande");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Fruitterie 440");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Frutta Si");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Fuel Station Unknown");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Fusee");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Future Shop");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Gap");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Garage Jos Perron");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Garage Sale");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Garage Sale Yen 514 823 8355");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Garderie Academie Kinder");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Garderie Educative Les Belles Frimousses");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Gare Centrale");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Globex2000");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Globo");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Google");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Google Play");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "GoogleApps");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Gouttieres Monteregie.com RBQ; 5649-7662-01");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Great-West");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Great-West Life");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Greich & Scaff");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Grossery Store");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "GroupOn");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Groupon");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Groupon.ca");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "H&M");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "HS Realties");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Hair World");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Halifax");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Hartman's Independent");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "HerbaMiel");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Hirondelle");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Hmshost market");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Home Depot");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Home Hardware / Quincaillerie Hogg");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Hopital General Juif");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Hotel Marriotte");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Hydro-Quebec");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "HydroSolution");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Hopital Charles-Le Moyne");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Hotel Le Voyageur (2250 boul Sainte-Anne, G1J 1Y2)");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "IDP PURCHASE - 1024-LANIEL ST-LAURE");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "IGA");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "IKEA");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Igor PRYSZLAK 514 861 9491");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Ihop Best Western");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Ikea");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Il Forneto");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Ile Aux Fleurs");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Ile aux fleur");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Impact Styles");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Indigo Parking");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Industria Coiffure Place");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Industrielle Alliance");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Insectarium");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Iris");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Irving");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Island Inkjet");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Italian");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "JGH Cafeteria");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "JGH Cafeteria");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Jardin Botanique");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Jardin Hatley");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Jean Coutu");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Jean-Drapeau");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Jean-Francois сосед");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Jewish General Hospital/Hopital General Juif");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Joe");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Joe Fresh");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "KABAB");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Kanda");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "KarateSportifBr 514-4677011 QC");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "KarateSportifBr 5144677011 PQ");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Kid Fundazzle");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Kijiji");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Kijiji.ca 514-995-1030");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Kim Phat");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Kojax");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Kojax Souflaki");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Koodo");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Krazy Cmak");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "L'Aubainerie");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "L'Equipeur");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "L'amour de Pain");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "L'inter marche");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "LCBO");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "La Baie");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "La Baie D'Hudson");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "La Baie d'Hudson");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "La Belle Province");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "La Ferme Quinn");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "La Fusee");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "La Poissonnerie Sami");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "La Salle Hospital");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "La Shop Informatique");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "La belle et la boeuf");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "La grillade (cabane a sucre)");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "LaSalle Hospital");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Lacopar");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Laundromat");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Laura Secord");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Lavigueur");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Lavigueur Champlain");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Le Balthazar");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Le Chateau");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Le Garderie Educative Les Belles Frimousses");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Le Parchemin");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Le Pourvoyeur");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Le Super Dollar");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Le Surcouf");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Leduc");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Legende Pastry");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Leonardo Panunto");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Les 3 Brasseurs");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Les 3 brasseurs");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Les Aliments Carne Inc");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Les Chausseures Rubino");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Les Cremes Glacees Jonathan");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Les Jets de St-Hubert Inc");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Les Vergers Lafrance");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Librairie Coop St-Jean-Sur-Richelieu");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Librairie Renaud Bray");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Librairie Renaud-Bray");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Lilian Iluta");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Lilian Iluta (514-433-5995,514-508-1761)");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Lily Vogue");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Linen Chest");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Lise Watier Cosmetiques");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Loblaws");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Loisirs Sportifs Cote Des Neiges");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Lozeau");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Luc 514 974 3703");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Lush");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Leon");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Leon Desjardins");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Leon Visa");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "MEC");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "MESRS: Prets et bourses");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "MESRS: Prets et bourses LOAN-VERS PRT BRC");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "MICC");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "MISC PAYMENT-GOUV. QUEBEC");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "MUNICIPAL PARKING CQPS VANCOUVER BC");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Machines a coudre Penelope");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Magasin Rossy");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Maison de Chemin");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Makkah");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Mange Sante");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Manoir de la Terrasse, Quebec");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Manulife");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "March Fruiterie Cite");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Marche C&T");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Marche De Fleurs Westminster");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Marche Fruite Cite");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Marche Fruiterie Cite");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Marche Frutterie Cite");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Marche KIM PHAT");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Marche Royal Plus");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Marche allemagne");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Marche fruiterie cite");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Marche public Longueuil");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Marche Ami");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Marche Lachine");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Marcil");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Marriote");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Martial Excavation");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Masako sushi");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Max Diner");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Maxi");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Maya Kroupnik");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "McDonald's");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Mega-Plex");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Merson Automotive Inc.");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Metro");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Mexx");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Michaels");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Mikes");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Mini Marche PET Airport");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Mission Bon Accueil");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Mobile Snap");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Mondiana");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Monsieur Fissure");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Mont Royal");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Mont Tremblant parking");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Mont-Tremblant");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Montreal");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Montreal Airport");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Montreal NDG");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Motel Jamm");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Motel au Soleil Couchant (945 boulevard Ste-Anne, G5M 1J1 Rimouski)");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Motto Pizza");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Mouline");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Mozart Alexis Nihon");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Mr. Pretzel");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Muffin Plus");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Multi Luminaire");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Municipalite de Tadoussac");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Murphy's On The Water");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Musee pour enfants");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "NSLC");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "National Bank");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Nature Ocean Chalets - Camping (400 Route 132 Ouest, G0C 2L0 Perce)");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Nature Ocйan Chalets - Camping (400 Route 132 Ouest, G0C 2L0 Perce)");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Needs");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Nettoyeur Orchid");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "New Egg");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "NewEgg.ca");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Newegg.ca");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Normandin");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Oka");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Okane Sushi Bar");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Okane sushi bar");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Old Navy");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Old Triangle Irish Ale House");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Oleg & Alena Khachova");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Omnivox");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Ordinateurs Canada");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Ordre Des Infirmieres");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Ottawa Souvenirs & Gifts");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Ovela");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "P.Delight/Amherst");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "PI-O");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "PJ");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "PJ Pub");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "PJ's Pub");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Palais Des Congres De Montreal");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Panda");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Panini Centre Eaton");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Parc Jean-Drapeau");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Parc Lachine");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Parc Mont Royal");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Parc Olympique");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Parc Safari");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Parc de la Chute-Montmorency");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Parc du Fjord-Du-Saguenay");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Paris Coiffure");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Park Avenue Toyota");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Pasticceria Alati-Caserta");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Patisserie de la Gare");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Patisserie la Legende Pastry");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Paul's Place Bed and Breakfast (369 Burnham Road, E7L 3W1 Bristol)");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "PayPal");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Payless");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Pearson Vue");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Pekarna");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Petro-Canada");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "PharmaPrix");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Pharmacie Jean-Pierre Rousseau");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Pharmaprix");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Pho Cali");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Photo Jocelyn Girard I 450-799-1089 QC");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Pierre Lafontaine 4632 Notre-Dame O, H4C 1S4 514 933 5304");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Pizza Pizza");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Place Oriental");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Postes Canada");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Potager Mont Rouge");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Poutine Centrale");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Premiers Pas - champlain");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Primier Pas");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Professional Air Duct Cleaning");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Provigo");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Proxim");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Proximed");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Public Mobile");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Quebec Etat Civil");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Queues De Castor");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Queues de castor/Beavertails");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Quebec");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Quebec ville");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "RAMQ");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "RBC");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "RQAP");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "RTL");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Radio");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Radioactif");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Radioplus Inc");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Ramonage Universel 450-462-2777");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Regie du Rentes");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Reitmans");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Renaissance");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Renaud-Bray");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Rest Shaan Tandoori");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Restaurant Amadeo");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Restaurant Creme & Cafe");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Restaurant Le Heron");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Restaurant Makkah");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Restaurant Makkah Halal");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Restaurant Nickels");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Restaurant Pnibrp");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Resto Du Village");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Resto le Maizerets");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Revenu Quebec");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Revenu Quebec");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Rialink");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Ripley's Aquarium");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Rococo");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Rona");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Reno Depot");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Reno Depot");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "S.R.A.M.");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "SAAQ");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "SAQ");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "SRAM");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "STM");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Safari");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Safe Bag");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Safe Bag Canada Inc");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Salade Arc en Ciel");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Sami Fruits");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "San Francisco");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Sandra Safulko");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Sao Sao");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Sears");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Second Cup");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Second Pizza");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Secure Bag");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Sepaq");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Service Canada");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Services Alimentaires Laniel St-Laurent");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Shell");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Shell Canada");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Sherpa Solutions RTLS");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Site Historique Maritime");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Skylon");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Smoke's Poutinerie");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Snowdon");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Souris Mini");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Souvenirs Ephesus");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Souvenirs de Vacances L'Aquilon");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Souvlaki George");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Spinelli");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Sports Aux Puces");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Sports Experts");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "St-Hubert");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "St-Jacques car wash");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "St-Jean-Sur-Richelieu-Transport");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "St-Peterburg Deli");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "St. Paul");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Starbucks");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Station Mont-Tremblant");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Station Service");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Steak Frites St-Paul");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Stefan auction");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Stefani");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Stephane Turner");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Stokes");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Studio Photo Rose");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Subway");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Super 8 Hotel & Suites Niagara Falls");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Super C");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Super Dollar");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Supermarche Akhavan");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Supermarche Akhavan");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "TEFAQ");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Table Rock Complex");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Taco Grillades");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Tandem 514 298 6245 Ольга и Денис");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Tapis Essgo Carpets");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Target");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Tatyana Onikichuk");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Teriyaki");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Terrasse");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Thai Express");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Thai Express");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "The Acorn Restaurant");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Thyme");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Tiki Ming");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Tim Horton's");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Tim Hortons");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Tout Pour Votre Maison");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Toyota Park Avenue");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Toyota Spinelli");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Toys'Я'us");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "ToysRus");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "ToysЯUs");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Trevi");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Turf Pub");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Turkish Airlines");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "UCCB/PUGE");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "UPS");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "UPS / AutomotiveTouchup.com");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "UQAM");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Uhaul");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Ultramar");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Ultramar Limitee");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "V Beaute");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "VILLE DE LONGUEUIL - TAXES");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Valerie Bergeron");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Verdun Hospital Fishman");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Verger Henryville");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Via Rail");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Via professional photo");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "ViaMedica");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Vices & Versa");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Vichy");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Videotron");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Village Des Valeurs");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Village des Valeurs");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Village des valeurs");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Village du Pere Noel");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Ville Montreal");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Vinci Park");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Vita Sana Cafe Resto");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Viva Italia");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Walmart");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "West Montreal");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Wilsons Fuels");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Windsor Hyper Bar Grill");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Winners");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Woodpile");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Wow!");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Y M -Y W H A MONTREAL PQ");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "YG Home Inspection Services");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Yamaska");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Yellow");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Yes");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Yokohame");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Yves Rocher");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Zellers");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "amazon.ca");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "bakery Snowdon");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "bento nouveau");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "cabana sucre");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "clinic");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "club entrepot");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "count REST");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "depanneur");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "eBay");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "eBay.ca");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "ebay");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "ebay.ca");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "ebay.com");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "expedia.ca");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "from Lena");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "hmv");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "indian shop, parc st.");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "initial state");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "jimmy the greek");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "kijiji");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "kijiji.ca");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "marche La Prairie");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "newegg.ca");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "parc Jean-Drapeau");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "parc Lachine");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "paypal");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "restaurant Nikas");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "resto Chinois");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "tuango");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "ville Montreal");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Econofitness");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Ile de Fleurs");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "ile Aux Fleurs");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Александр 514-442-9434");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Александр 514-916-6317, 8151 Montreal-Toronto, H4E2H8");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Алексей 514 994 1229");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Алексей 514 994 1229, 2039, chemin Chambly j4j");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Алексей/Александр 514 994 1229, 2039, chemin Chambly j4j");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Алина Дима");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Алина Шеремет");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Алина,Дима, Данила - Квебек");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Валентина");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Валя ДР");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Валя Молдова");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Ваня");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Ваня Омск ДР");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Ваня и Ира, Наташа и Jean-Robert Josef");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Виктор (514-571-6483)");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Денис кузова 514-992-0935");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Диана");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Дима Р: заправка Costco");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Дима Р: машина на прокат U-Haul");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Дима от Роман Колесник (5148652455)");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Жанна");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Женя\\Лена");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Ира Киргизия");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Карен Бабаян");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Кошелевы");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Лена Женя");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Лена и Женя");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Лилиан бухгалтер");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Люда");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Люда Влад");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Люк");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "М с работы на Laurier");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Маша");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Наташа");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Наташа ДР");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Николай (514-343-0543)");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Олег от Роман Колесник (5148652455)");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Павел Калашников 514-638-8377");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Павел Калашников 514-638-8377, 5286 Cote St Paul, H4C 1X1");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Паша Фуртуна");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Руденчуки");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Слава");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Татьяна");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Татьяна Dollarama");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Фишман");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Эдуард");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Юля и Вакула");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "Юля-Вакула");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "баклажанчик");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "индус");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "копилка");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "корабль");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "логопед");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "мама Галя");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "мама, папа");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "мама,папа");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "мама,папа: обнуление");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "одногруппнице");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "от Славы (514-651-7657) Дмитрий(514-969-1008), Юра (514-576-5977)");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "подвал");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "турки");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "у Люды");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "у бассейна");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "у дороги дедушка");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "у дядьки с рук");
        StringSimilarity.printLevenshteinDistanceSimilarity(levenshteinDistance, "AMT", "через Славу");

        long end = System.nanoTime();
        long duration = end - start;
        System.out.println("duration (nano sec): " + duration);
        System.out.println("duration (millis): " + TimeUnit.NANOSECONDS.toMillis(duration));
    }
}
