/********************************************************************
* TFileStringDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TFileStringDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTFileStringDict();
extern void G__cpp_setup_inheritanceTFileStringDict();
extern void G__cpp_setup_typetableTFileStringDict();
extern void G__cpp_setup_memvarTFileStringDict();
extern void G__cpp_setup_globalTFileStringDict();
extern void G__cpp_setup_memfuncTFileStringDict();
extern void G__cpp_setup_funcTFileStringDict();
extern void G__set_cpp_environmentTFileStringDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TFileString.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TFileStringDictLN_TClass;
extern G__linked_taginfo G__TFileStringDictLN_TBuffer;
extern G__linked_taginfo G__TFileStringDictLN_TMemberInspector;
extern G__linked_taginfo G__TFileStringDictLN_TObject;
extern G__linked_taginfo G__TFileStringDictLN_string;
extern G__linked_taginfo G__TFileStringDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TFileStringDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TFileStringDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TFileStringDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TFileStringDictLN_TObjString;
extern G__linked_taginfo G__TFileStringDictLN_TFileString;
extern G__linked_taginfo G__TFileStringDictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__TFileStringDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
