package ex22;

public class Ex2202TopDownMergeSortTraces {
  
/* p284
  2.2.2  Give traces, in the style of the trace given with Algorithm 2.4, showing
   how the keys  E A S Y Q U E S T I O N  are sorted with top-down mergesort.
   
    Top-down mergesort call trace:
   
          sort(a,0,11)
            sort(a,0,5)               sort right half
              sort(a,0,2)
                sort(a,0,1)
                  merge(a,0,0,1)
                merge(a,0,1,2)
              sort(a,3,5)
                sort(a,3,4)
                  merge(a,3,3,4)
                merge(a,3,4,5)
              merge(a,0,2,5)
            sort(a,6,11)              sort left half
              sort(a,6,8)
                sort(a,6,7)
                  merge(a,6,6,7)
                merge(a,6,7,8)
              sort(a,9,11)
                sort(a,9,10)
                  merge(a,9,9,10)
                merge(a,9,10,11)
              merge(a,6,8,11)
            merge(a,0,5,11)           merge results

   
    Trace of merge results for top-down mergesort:
       
                                              [a]
                       lo   hi   0  1  2  3  4  5  6  7  8  9 10 11  
                        |   |    -----------------------------------
                        V   V     E  A  S  Y  Q  U  E  S  T  I  O  N  
                merge(a,0,0,1)   {A  E} S  Y  Q  U  E  S  T  I  O  N 
              merge(a,0,1,2)     {A  E  S} Y  Q  U  E  S  T  I  O  N  
                merge(a,3,3,4)    A  E  S {Q  Y} U  E  S  T  I  O  N  
              merge(a,3,4,5)      A  E  S {Q  U  Y} E  S  T  I  O  N  
            merge(a,0,2,5)       {A  E  Q  S  U  Y} E  S  T  I  O  N  
                merge(a,6,6,7)    A  E  Q  S  U  Y {E  S} T  I  O  N  
              merge(a,6,7,8)      A  E  Q  S  U  Y {E  S  T} I  O  N  
                merge(a,9,9,10)   A  E  Q  S  U  Y  E  S  T {I  O} N  
              merge(a,9,10,11)    A  E  Q  S  U  Y  E  S  T {I  N  O} 
            merge(a,6,8,11)       A  E  Q  S  U  Y {E  I  N  O  S  T} 
          merge(a,0,5,11)        {A  E  E  I  N  O  Q  S  S  T  U  Y}   
          
          
   The trace data was generated by running sort.MergeTopDown.sort2(a);
       
*/
  
  public static void main(String[] args) {

  }

}
